### ISSUE TITLE
Missing classes from hype_2.12

### ISSUE THREAD

**Issue by andrewsmartin** [spotify/hype#36]
I'm setting up a Scala project to experiment with Hype, and the `com.spotify.hype_2.12` artifact doesn't contain several classes found in the 2.11 artifact, for example `GkeSubmitter`. Normally the non-version-specific code would go in the general `com.spotify.hype.submitter` artifact, although that is already its own Java module. Is it possible to combine them?

**Comment by andrewsmartin** [comment]
Or maybe an alternative is to have a `hype-scala` module, with 2.11- and 2.12-specific code in `src/main/scala_2.11` and `src/main/scala_2.12` respectively.

**Comment by rouzwawi** [comment]
If we can have a shared Scala module, and still have it compile to both 2.11 and 2.12 jars, then that would be a good solution.

I haven't investigated this soo much, but my initial gut feeling got me thinking that it would require some symlinking of the common sources. Or some other hackery with the Scala compiler plugin to make it build different targeted jars with different sources, and some shared sources.

**Comment by andrewsmartin** [comment]
I think it should be doable since `sbt` supports this via cross-building. If you're +1 on the idea of having a `hype-scala` module I can submit a PR.
